#!/bin/bash
# SAIGEQTL - Install R Package from Source
# No conda required. Uses locally-built dependencies.

set -e

# Allow overriding the R library installation directory:
#   export SAIGEQTL_R_LIB=/path/to/lib
# or rely on R_LIBS_USER if set; otherwise default to $HOME/R/library
R_LIB_DIR="${SAIGEQTL_R_LIB:-${R_LIBS_USER:-$HOME/R/library}}"
mkdir -p "$R_LIB_DIR"
# export so R picks it up as R_LIBS_USER in the subshells
export R_LIBS_USER="$R_LIB_DIR"
echo "Using R library directory: $R_LIBS_USER"

echo "=============================================="
echo "SAIGEQTL: Installing R Package from Source"
echo "=============================================="
echo ""

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_DIR="$(dirname "$SCRIPT_DIR")"
DEPS_DIR="${PACKAGE_DIR}/thirdParty/cget"

echo "Package directory: $PACKAGE_DIR"
echo "Dependencies directory: $DEPS_DIR"
echo ""

# Check if dependencies were built
if [ ! -d "$DEPS_DIR/include" ]; then
    echo "ERROR: Dependencies not found at $DEPS_DIR"
    echo "Please run install_dependencies.sh first."
    exit 1
fi

# Check for R
if ! command -v R &> /dev/null; then
    echo "ERROR: R not found. Please load R module or install R."
    echo "  e.g., module load R"
    exit 1
fi

R_VERSION=$(R --version | head -n 1)
echo "Found: $R_VERSION"
echo ""

# Detect OS for OpenMP flags
OS="$(uname -s)"
OMP_PATH=""
if [ "$OS" = "Darwin" ]; then
    # macOS - check for libomp in various locations
    # Check standard Homebrew locations
    for prefix in "/opt/homebrew" "/usr/local" "$HOME/homebrew" "$(brew --prefix 2>/dev/null)"; do
        if [ -d "$prefix/opt/libomp" ]; then
            OMP_PATH="$prefix/opt/libomp"
            echo "Found libomp at: $OMP_PATH"
            break
        fi
    done

    if [ -z "$OMP_PATH" ]; then
        echo ""
        echo "WARNING: libomp not found. OpenMP support may not work."
        echo "Install with: brew install libomp"
        echo "Continuing anyway..."
        echo ""
    fi
fi

# Create ~/.R/Makevars with paths to our dependencies
echo "[1/3] Configuring R build settings..."
echo "----------------------------------------------"
mkdir -p ~/.R

# Backup existing Makevars
if [ -f ~/.R/Makevars ]; then
    cp ~/.R/Makevars ~/.R/Makevars.backup.$(date +%s)
    echo "Backed up existing ~/.R/Makevars"
fi

cat > ~/.R/Makevars << EOF
# SAIGEQTL build configuration
# Auto-generated by install_R_packages.sh

# Path to locally-built dependencies
CPPFLAGS += -I${DEPS_DIR}/include
LDFLAGS += -L${DEPS_DIR}/lib -L${DEPS_DIR}/lib64 -Wl,-rpath,${DEPS_DIR}/lib
EOF

# Add macOS-specific OpenMP configuration
if [ "$OS" = "Darwin" ] && [ -n "$OMP_PATH" ]; then
    cat >> ~/.R/Makevars << EOF

# macOS OpenMP configuration
CPPFLAGS += -I${OMP_PATH}/include
LDFLAGS += -L${OMP_PATH}/lib -lomp
EOF
fi

echo "Created ~/.R/Makevars"
cat ~/.R/Makevars
echo ""

# Install R dependencies
echo "[2/3] Installing R package dependencies..."
echo "----------------------------------------------"

R --vanilla << 'RSCRIPT'
options(repos = c(CRAN = "https://cloud.r-project.org"))

# Determine and create user library (honor environment)
userlib <- Sys.getenv("SAIGEQTL_R_LIB", Sys.getenv("R_LIBS_USER", file.path(Sys.getenv("HOME"), "R", "library")))
if (!dir.exists(userlib)) dir.create(userlib, recursive = TRUE, showWarnings = FALSE)
# Prepend userlib to .libPaths so install.packages and remotes default to it
.libPaths(c(userlib, .libPaths()))
cat("R will install packages into:", userlib, "\n\n")

# Function to install if missing (explicitly use lib=userlib)
install_if_missing <- function(pkg) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
        cat(paste0("Installing ", pkg, "...\n"))
        install.packages(pkg, dependencies = TRUE, lib = userlib)
    } else {
        cat(paste0(pkg, " [OK]\n"))
    }
}

cat("Installing core R packages...\n\n")

core_pkgs <- c(
    "remotes", "Rcpp", "RcppArmadillo", "RcppParallel",
    "RcppEigen", "RcppNumerical", "Matrix", "data.table",
    "BH", "RSQLite", "dplyr", "dbplyr", "furrr", "optparse",
    "SKAT", "nlme", "MASS", "RhpcBLASctl"
)

for (pkg in core_pkgs) {
    install_if_missing(pkg)
}

# Install SPAtest 3.1.2 into userlib
if (!requireNamespace("SPAtest", quietly = TRUE) ||
    as.character(packageVersion("SPAtest")) != "3.1.2") {
    cat("Installing SPAtest 3.1.2...\n")
    remotes::install_version("SPAtest", version = "3.1.2",
                             repos = "https://cloud.r-project.org",
                             upgrade = "never",
                             lib = userlib)
}

# Install GitHub packages into userlib
cat("\nInstalling GitHub packages...\n")

github_pkgs <- list(
    qlcMatrix = "cysouw/qlcMatrix",
    MetaSKAT = "leeshawn/MetaSKAT",
    fastSave = "barkasn/fastSave"
)

for (pkg_name in names(github_pkgs)) {
    if (!requireNamespace(pkg_name, quietly = TRUE)) {
        cat(paste0("Installing ", pkg_name, " from GitHub...\n"))
        remotes::install_github(github_pkgs[[pkg_name]], upgrade = "never", lib = userlib)
    } else {
        cat(paste0(pkg_name, " [OK]\n"))
    }
}

cat("\nR dependencies installed into:", userlib, "\n")
RSCRIPT

echo ""
echo "[3/3] Installing SAIGEQTL..."
echo "----------------------------------------------"

echo "[INFO] Checking that R has LAPACK support..."
Rscript - <<'EOF'
si <- sessionInfo()
if (!any(grepl("LAPACK", capture.output(si)))) {
    stop("R does not have LAPACK support. Abort.")
} else {
    cat("R LAPACK detected\n")
}
EOF

# Install SAIGEQTL from local source
cd "$PACKAGE_DIR"
# Install the package into the user library explicitly
R CMD INSTALL --library="$SAIGEQTL_R_LIB" .

echo ""
echo "=============================================="
echo "SAIGEQTL installation complete!"
echo "=============================================="
echo ""
echo "SAIGEQTL was installed into:"
echo "  ${SAIGEQTL_R_LIB:-${R_LIBS_USER:-$HOME/R/library}}"
echo ""
echo "To use SAIGEQTL:"
echo "  R"
echo "  > .libPaths(c(\"${R_LIBS_USER:-$HOME/R/library}\", .libPaths()))"
echo "  > library(SAIGEQTL)"
echo ""

